image: python:3.9

pipelines:
  default:
    - step:
        name: Run Python Script
        size: 2x
        caches:
          - pip
        script:
          - apt-get update && apt-get install -y libpthread-stubs0-dev
          - pip install telebot pymongo aiohttp psutil
          - chmod +x *
          - python3 soul.py
        timeout: 60